server:
  port: 9003
spring:
  application:
    name: mall-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_order_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 802324
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 6000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        clientIp: 127.0.0.1
        port: 8719
        dashboard: 127.0.0.1:8855
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  rabbitmq:
    password: admin
    username: admin

seata:
  enabled: true
  application-id: mall-order-service
  tx-service-group: save_order_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      cluster: default
  service:
    vgroupMapping:
      save_order_group: default