server:
  port: 9050
spring:
  application:
    name: mall-gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        clientIp: 127.0.0.1
        port: 8719
        dashboard: 127.0.0.1:8855
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://mall-user-service
          order: 1
          predicates:
            - Path=/user/mall/**
        - id: goods-service-route
          uri: lb://mall-product-service
          order: 1
          predicates:
            - Path=/goods/mall/**
        - id: goods-service-route-2
          uri: lb://mall-product-service
          order: 1
          predicates:
            - Path=/categories/mall/**
        - id: cart-service-route
          uri: lb://mall-cart-service
          order: 1
          predicates:
            - Path=/shop-cart/**
        - id: order-service-route
          uri: lb://mall-order-service
          order: 1
          predicates:
            - Path=/order/mall/**
            - Path=/mall/address/**
        - id: order-service-route2
          uri: lb://mall-order-service
          order: 1
          predicates:
            - Path=/mall/address/**
  redis:
    database: 13
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000
