server:
  port: 9002
spring:
  application:
    name: mall-user-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_user_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 802324
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8858
  redis:
    host: 121.36.29.254
    port: 6379
    database: 0
    timeout: 5000
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

